### PR TITLE
Added Colors, Legends, Sprites/Includes and constants to PlantUML Sheet

### PR DESCRIPTION
**Pull request by PTangeL**
Adding more documentation about Colors and Legend to PlantUML Sheet

### CODE REVIEW

**Comment by PTangeL** [comment]
Just missclicked on close.

**Comment by ogom** [comment]
@PTangeL  An example of color is wonderful. The hosting URL is not `ptangel.github.io`, but` ogom.github.io` seems good, but would you change it?

**Comment by PTangeL** [comment]
Yeah u are right, i was testing to see if it all worked, but forgot to revert the url

**Comment by PTangeL** [comment]
PS: I merged the other branch into master, so you can put the github pages from master ;)

**Pull request merged**
